### ISSUE TITLE
Get the Electrons test working

### ISSUE THREAD

**Issue by gordonwatts** [iris-hep/func_adl.xAOD#23]
That Marc wants to use this for performance:

- Electorn E, pt, phi, eta
- Muon E, pt, phi, eta

If those work, then we are done with this issue. Past the proper `quastle` text into this bug report when we have it. Once @mweinberg2718 verifies, we are done.

**Comment by gordonwatts** [comment]
Ah! Nothing is wrong - I totally forgot. The problem is the `quastle` doesn't understand sub-scripts. @masonproffitt fixed that. I've set everything up to use version 0.3 of the library. I now have to understand the proper workflow to get it back into the code generator.

Here is what your text should look like to grab all the 8 columns:

```
(call ResultTTree (call Select (call Select (call EventDataset (list 'localds:bogus')) (lambda (list e) (list (call (attr e 'Electrons') 'Electrons') (call (attr e 'Muons') 'Muons')))) (lambda (list e) (list (call (attr (subscript e 0) 'Select') (lambda (list ele) (call (attr ele 'E')))) (call (attr (subscript e 0) 'Select') (lambda (list ele) (call (attr ele 'pt')))) (call (attr (subscript e 0) 'Select') (lambda (list ele) (call (attr ele 'phi')))) (call (attr (subscript e 0) 'Select') (lambda (list ele) (call (attr ele 'eta')))) (call (attr (subscript e 1) 'Select') (lambda (list mu) (call (attr mu 'E')))) (call (attr (subscript e 1) 'Select') (lambda (list mu) (call (attr mu 'pt')))) (call (attr (subscript e 1) 'Select') (lambda (list mu) (call (attr mu 'phi')))) (call (attr (subscript e 1) 'Select') (lambda (list mu) (call (attr mu 'eta'))))))) (list 'e_E' 'e_pt' 'e_phi' 'e_eta' 'mu_E' 'mu_pt' 'mu_phi' 'mu_eta') 'forkme' 'dude.root')
```

**Comment by gordonwatts** [comment]
When we run the integration test, this does not work. So we need to reopen to figure out how this is failing.

From the code generator:
```
192.168.29.136 - - [23/Jan/2020:10:36:38 +0000] "POST /servicex/generated-code HTTP/1.1" 200 5681 "-" "python-requests/2.22.0"
Internal Error: attempted to get C++ representation for AST note "List(elts=[Call(func=CPPCodeValue(), args=[Str(s='Electrons')], keywords=[]), Call(func=CPPCodeValue(), args=[Str(s='Muons')], keywords=[])], ctx=Load())", but failed.
Traceback (most recent call last):
  File "/home/servicex/servicex/code_generator_service/generate_code.py", line 90, in post
    zip_data = translate_text_ast_to_zip(code)
  File "/home/servicex/servicex/code_generator_service/generate_code.py", line 73, in translate_text_ast_to_zip
    r = use_executor_xaod_hash_cache(a, tempdir)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/exe_atlas_xaod_hash_cache.py", line 59, in use_executor_xaod_hash_cache
    f_spec = exe.write_cpp_files(exe.apply_ast_transformations(a), query_file_path)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/atlas_xaod_executor.py", line 103, in write_cpp_files
    result_rep = qv.get_rep(ast)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 175, in get_rep
    self.generic_visit(node) if use_generic_visit else self.visit(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 520, in visit_Call
    r = FuncADLNodeVisitor.visit_Call(self, call_node)
  File "/usr/local/lib/python3.7/site-packages/func_adl/ast/func_adl_ast_utils.py", line 78, in visit_Call
    return visitor(node, args)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 675, in call_ResultTTree
    self.generic_visit(source)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/ast.py", line 281, in generic_visit
    self.visit(value)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 520, in visit_Call
    r = FuncADLNodeVisitor.visit_Call(self, call_node)
  File "/usr/local/lib/python3.7/site-packages/func_adl/ast/func_adl_ast_utils.py", line 78, in visit_Call
    return visitor(node, args)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 792, in call_Select
    seq = self.as_sequence(source)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 237, in as_sequence
    rep = self.get_rep(generation_ast)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 175, in get_rep
    self.generic_visit(node) if use_generic_visit else self.visit(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 144, in visit
    r = FuncADLNodeVisitor.visit(self, node)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 535, in visit_Subscript
    v = self.get_rep(node.value)
  File "/usr/local/lib/python3.7/site-packages/func_adl_xAOD/backend/xAODlib/ast_to_cpp_translator.py", line 181, in get_rep
    raise BaseException('Internal Error: attempted to get C++ representation for AST note "{0}", but failed.'.format(ast.dump(node)))
BaseException: Internal Error: attempted to get C++ representation for AST note "List(elts=[Call(func=CPPCodeValue(), args=[Str(s='Electrons')], keywords=[]), Call(func=CPPCodeValue(), args=[Str(s='Muons')], keywords=[])], ctx=Load())", but failed.
192.168.29.136 - - [23/Jan/2020:10:40:47 +0000] "POST /servicex/generated-code HTTP/1.1" 500 251 "-" "python-requests/2.22.0"
```

**Comment by masonproffitt** [comment]
Ah, I know why. `query_ast_visitor` doesn't have a `visit_List()`. Without the qastle translation, the `tuple` in your test stayed an `ast.Tuple` node and `visit_Tuple()` was called. But `qastle` doesn't have tuples; it just turns them into `(list)`s since there's no meaningful distinction in the AST language. When it gets back to your backend, it's been translated into a Python `ast.List`, so the roundtrip isn't an identity operation.

In any case, the solution should just be to add a `visit_List()` (probably just redirecting to `visit_Tuple()` or vice versa). I guess all of your tests use only `tuple`s and not any explicit `list`s.

**Comment by gordonwatts** [comment]
Ok - I've now added tests that look at this with lists and with tuples - and they all work and C++ code is generated. It could be there is another subtle difference that qastle is introducing into the translation. Clearly, I need to put in an explicit test here that tests this.

**Comment by gordonwatts** [comment]
Yes! That is the problem - something else is getting switched to. See the check out right below.

**Comment by gordonwatts** [comment]
Let's see if we can track this down. Here is a before/after:

```
before: Call(func=Name(id='ResultTTree', ctx=Load()), args=[Call(func=Name(id='Select', ctx=Load()), args=[Call(func=Name(id='Select', ctx=Load()), args=[Call(func=Name(id='EventDataset', ctx=Load()), args=[List(elts=[Str(s='file:///root.root')], ctx=Load())], keywords=[]), Lambda(args=arguments(args=[arg(arg='e', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=List(elts=[Call(func=Attribute(value=Name(id='e', ctx=Load()), attr='Electrons', ctx=Load()), args=[Str(s='Electrons')], keywords=[]), Call(func=Attribute(value=Name(id='e', ctx=Load()), attr='Muons', ctx=Load()), args=[Str(s='Muons')], keywords=[])], ctx=Load()))], keywords=[]), Lambda(args=arguments(args=[arg(arg='e', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=List(elts=[Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='E', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='pt', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='phi', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='eta', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='E', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='pt', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='phi', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='eta', ctx=Load()), args=[], keywords=[]))], keywords=[])], ctx=Load()))], keywords=[]), List(elts=[Str(s='e_E'), Str(s='e_pt'), Str(s='e_phi'), Str(s='e_eta'), Str(s='mu_E'), Str(s='mu_pt'), Str(s='mu_phi'), Str(s='mu_eta')], ctx=Load()), Str(s='forkme'), Str(s='dude.root')], keywords=[])
after: Module(body=[Expr(value=Call(func=Name(id='ResultTTree', ctx=Load()), args=[Call(func=Name(id='Select', ctx=Load()), args=[Call(func=Name(id='Select', ctx=Load()), args=[Call(func=Name(id='EventDataset', ctx=Load()), args=[List(elts=[Str(s='file:///root.root')], ctx=Load())], keywords=[]), Lambda(args=arguments(args=[arg(arg='e', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=List(elts=[Call(func=Attribute(value=Name(id='e', ctx=Load()), attr='Electrons', ctx=Load()), args=[Str(s='Electrons')], keywords=[]), Call(func=Attribute(value=Name(id='e', ctx=Load()), attr='Muons', ctx=Load()), args=[Str(s='Muons')], keywords=[])], ctx=Load()))], keywords=[]), Lambda(args=arguments(args=[arg(arg='e', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=List(elts=[Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='E', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='pt', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='phi', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='eta', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='E', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='pt', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='phi', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='eta', ctx=Load()), args=[], keywords=[]))], keywords=[])], ctx=Load()))], keywords=[]), List(elts=[Str(s='e_E'), Str(s='e_pt'), Str(s='e_phi'), Str(s='e_eta'), Str(s='mu_E'), Str(s='mu_pt'), Str(s='mu_phi'), Str(s='mu_eta')], ctx=Load()), Str(s='forkme'), Str(s='dude.root')], keywords=[]))])
```

**Comment by gordonwatts** [comment]
Ok - after stripping out the module stuff by hand, we still get the failure:

```
before: Call(func=Name(id='ResultTTree', ctx=Load()), args=[Call(func=Name(id='Select', ctx=Load()), args=[Call(func=Name(id='Select', ctx=Load()), args=[Call(func=Name(id='EventDataset', ctx=Load()), args=[List(elts=[Str(s='file:///root.root')], ctx=Load())], keywords=[]), Lambda(args=arguments(args=[arg(arg='e', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=List(elts=[Call(func=Attribute(value=Name(id='e', ctx=Load()), attr='Electrons', ctx=Load()), args=[Str(s='Electrons')], keywords=[]), Call(func=Attribute(value=Name(id='e', ctx=Load()), attr='Muons', ctx=Load()), args=[Str(s='Muons')], keywords=[])], ctx=Load()))], keywords=[]), Lambda(args=arguments(args=[arg(arg='e', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=List(elts=[Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='E', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='pt', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='phi', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='eta', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='E', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='pt', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='phi', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='eta', ctx=Load()), args=[], keywords=[]))], keywords=[])], ctx=Load()))], keywords=[]), List(elts=[Str(s='e_E'), Str(s='e_pt'), Str(s='e_phi'), Str(s='e_eta'), Str(s='mu_E'), Str(s='mu_pt'), Str(s='mu_phi'), Str(s='mu_eta')], ctx=Load()), Str(s='forkme'), Str(s='dude.root')], keywords=[])
after: Call(func=Name(id='ResultTTree', ctx=Load()), args=[Call(func=Name(id='Select', ctx=Load()), args=[Call(func=Name(id='Select', ctx=Load()), args=[Call(func=Name(id='EventDataset', ctx=Load()), args=[List(elts=[Str(s='file:///root.root')], ctx=Load())], keywords=[]), Lambda(args=arguments(args=[arg(arg='e', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=List(elts=[Call(func=Attribute(value=Name(id='e', ctx=Load()), attr='Electrons', ctx=Load()), args=[Str(s='Electrons')], keywords=[]), Call(func=Attribute(value=Name(id='e', ctx=Load()), attr='Muons', ctx=Load()), args=[Str(s='Muons')], keywords=[])], ctx=Load()))], keywords=[]), Lambda(args=arguments(args=[arg(arg='e', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=List(elts=[Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='E', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='pt', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='phi', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='ele', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='ele', ctx=Load()), attr='eta', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='E', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='pt', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='phi', ctx=Load()), args=[], keywords=[]))], keywords=[]), Call(func=Attribute(value=Subscript(value=Name(id='e', ctx=Load()), slice=Index(value=Num(n=1)), ctx=Load()), attr='Select', ctx=Load()), args=[Lambda(args=arguments(args=[arg(arg='mu', annotation=None)], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=Call(func=Attribute(value=Name(id='mu', ctx=Load()), attr='eta', ctx=Load()), args=[], keywords=[]))], keywords=[])], ctx=Load()))], keywords=[]), List(elts=[Str(s='e_E'), Str(s='e_pt'), Str(s='e_phi'), Str(s='e_eta'), Str(s='mu_E'), Str(s='mu_pt'), Str(s='mu_phi'), Str(s='mu_eta')], ctx=Load()), Str(s='forkme'), Str(s='dude.root')], keywords=[])
```

**Comment by gordonwatts** [comment]
This is so frustrating - because when I feed the qastle line in func_adl_xAOD tests it works, but it fails when in the CodeGen context. I'm going to reset all version numbers just in case.

**Comment by gordonwatts** [comment]
GAAA! Repackage with new version numbers and everything works.

- I might have missed a file (but git logs indicate that didn't happen)
- Maybe there was an eggs file around or similar left over and I didn't clean up first.

That was almost 6 hours of debugging to get that there! Thought one might be tempted to say that was because we didn't have the testing infrastructure to do these tests quickly!

**Comment by gordonwatts** [comment]
This finally works - gaa! As they say.
